deployapp/urls.py
from django.contrib import admin
from django.urls import path
from testapp import views
from django.conf.urls import url


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^create$',views.Create.as_view(),name='create'),
    url(r'^list$',views.EmpList.as_view(),name='list'),
    url(r'detail/(?P<pk>\d+)/$',views.detail.as_view()),
    url(r'update/(?P<pk>\d+)/$',views.update.as_view()),
    url(r'delete/(?P<pk>\d+)/$',views.delete.as_view(),name='delete')

]

testapp/models.py
from django.db import models
from django.urls import reverse

class Employee(models.Model):
    eid = models.IntegerField()
    ename = models.CharField(max_length=64)
    esal = models.FloatField()
    eaddr = models.CharField(max_length=64)


    def __str__(self):
        return self.ename

    def get_absolute_url(self):
        return reverse('list')

testapp/forms.py
from django import forms
from.models import Employee

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'

testapp/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView,UpdateView
from django.views.generic import ListView,DetailView,DeleteView
from .models import Employee
from django.urls import reverse_lazy


class EmpList(ListView):
    model = Employee
    template_name = 'list.html'

class Create(CreateView):
    model = Employee
    template_name = 'create.html'
    fields = ("__all__")

class detail(DetailView):
    model = Employee
    template_name = 'detail.html'

class update(UpdateView):
    model = Employee
    template_name = 'update.html'
    fields = '__all__'
class delete(DeleteView):
    model = Employee
    template_name = 'delete.html'
    success_url = reverse_lazy('list')

templates/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>This is create page!!</h1>
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Submit">

</form>
</body>
</html>

templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Are you want to Delete</h1>
<form method="post" enctype="multipart/form-data">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value=" CONFIRM DELETE">
    </form><br>

 <a href="{% url 'list' %}">CANCEL</a>
</body>
</html>

templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>This is The Detail of Employe</h1>
<table>
    <th>Detail of Employee</th>
    <tr>
    <th>ENo</th>
    <th>Name</th>
    <th>Salary</th>
    <th>Address</th>
    </tr>
    <tr>
        <td>{{ employee.eno }}</td>
        <td>{{ employee.ename }}</td>
        <td>{{employee.esal  }}</td>
        <td>{{ employee.eaddr }}</td>
    </tr>

</table>
<!--<div><a href="{% url 'delete' pk=employee.pk%}">DELETE</a>

</div>
-->
</body>
</html>

templates/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List</title>
</head>
<body><div align="center">
<h1>This is list view!!</h1>
{% for x in employee_list %}<br/>
    {{ x.pk }}<br/>
    {{ x.eno }}<br/>
    {{ x.ename }}<br/>
    {{ x.esal }}<br/>
    {{ x.eaddr }}<br/>
{% endfor %}
</div>
</body>
</html>

templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update Page</title>
</head>
<body>
<h>This Is Update Page</h>
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit"value="Update">
</form>
</body>
</html>